In [1]:
import numpy as np
import matplotlib as plt


In [2]:
a = np.array([2, 3, 4])

In [3]:
a.dtype

dtype('int64')

In [6]:
a.shape

(3,)

In [7]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])

In [8]:
b.dtype

dtype('float64')

In [22]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones([2, 3, 4], dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [15]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [18]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)


In [20]:
c = a - b
c

array([20, 29, 38, 47])

In [23]:
b**2

array([0, 1, 4, 9])

In [24]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [25]:
a < 35

array([ True,  True, False, False])

In [26]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])


In [27]:
A * B     # elementwise product


array([[2, 0],
       [0, 4]])

In [28]:
A @ B     # matrix product


array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)  # another matrix product